# Generated by Django 4.2.5 on 2023-11-09 14:29

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('mesaj', models.TextField()),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim',
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(max_length=155)),
                ('desing', models.CharField(max_length=120)),
                ('services', models.CharField(max_length=120)),
                ('team', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('process', models.TextField()),
                ('result', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('oneimage', models.ImageField(default='default_image.jpg', upload_to='news_images/')),
                ('twoimage', models.ImageField(default='default_image.jpg', upload_to='news_images/')),
                ('threeimage', models.ImageField(default='default_image.jpg', upload_to='news_images/')),
                ('fourimage', models.ImageField(default='default_image.jpg', upload_to='news_images/')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title', unique=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
                'db_table': 'Post',
            },
        ),
    ]
