# Generated by Django 4.2.5 on 2023-09-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Post'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
