# Generated by Django 4.2.5 on 2023-09-13 12:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_post_options_alter_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='baslik', unique=True),
        ),
    ]
